on:
  push:
    branches: master
    # branches-ignore:
    #   - '**'

name: Generate book

jobs:
  build:
    runs-on: macOS-latest
    env:
      RGL_USE_NULL: true
      BING_MAPS_KEY: ${{ secrets.BING_MAPS_KEY }}
      GGMAP_GOOGLE_API_KEY: ${{ secrets.GGMAP_GOOGLE_API_KEY }}
      GITHUB_PAT: ${{ secrets.TFA }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create and populate .Renviron file
        run: |
          echo BING_MAPS_KEY="${{ secrets.BING_MAPS_KEY }}" >> ~/.Renviron
          echo GGMAP_GOOGLE_API_KEY="{{ secrets.GGMAP_GOOGLE_API_KEY }}" >> ~/.Renviron
          shell: bash

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install dependicies
        run: |
          brew install pandoc
          brew install libgit2

      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: book/_bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Render book
        run: Rscript book/render_book.R

      - name: Commit results
        run: |
          git config user.email "junk@relund.dk"
          git config user.name "Lars Relund"
          git add .
          git commit --allow-empty -am 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git pull --rebase
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"