on:
  push:
    branches: [main, master]
    # branches-ignore:
    #   - '**'

name: Render book (Ubuntu)

jobs:
  Render-book-ubuntu:
    runs-on: ubuntu-latest
    env:
      RGL_USE_NULL: true
      BING_MAPS_API_KEY: ${{ secrets.BING_MAPS_KEY }}
      GGMAP_GOOGLE_API_KEY: ${{ secrets.GGMAP_GOOGLE_KEY }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install Curl
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - uses: r-lib/actions/setup-renv@v1

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Render book
        run: Rscript book/render_book.R